### ISSUE TITLE
TypeError: Cannot add property noFallthroughCasesInSwitch, object is not extensible

### ISSUE THREAD

**Issue by nelsonc24** [alexandr-g/cra-template-typescript-redux#123]
Hi,

I am getting an error after running _yarn create react-app your-project-name --template typescript-redux_ or _npx create-react-app your-project-name --template typescript-redux_, at the end of the installation shows the error: **TypeError: Cannot add property noFallthroughCasesInSwitch, object is not extensible
    at verifyTypeScriptSetup (/Volumes/Transcend/Devs/reactjs/your-project-name/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js:231:45)
    at module.exports (/Volumes/Transcend/Devs/reactjs/your-project-name/node_modules/react-scripts/scripts/init.js:336:5)
    at [eval]:3:14
    at Script.runInThisContext (vm.js:120:20)
    at Object.runInThisContext (vm.js:311:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at evalScript (internal/process/execution.js:94:25)
    at internal/main/eval_string.js:23:3**

Hope this info can be helpful to you to fix the issue. Thank you in advance.

Regards,

**Comment by alexandr-g** [comment]
Hi Nelson,

Thanks for repotting. I've opened https://github.com/alexandr-g/cra-template-typescript-redux/pull/124 to fix it. You could try again the new release. 

Looks like the issues is linked to the https://github.com/facebook/create-react-app/issues/9429 

Best regards,
Alex
